### ISSUE TITLE
Broken compose

### ISSUE THREAD

**Issue by mageuser** [yorick2/Magento-2-add-products-to-categories-in-admin#1]
Hello, im trying update magento and got this:

```
Could not fetch https://api.github.com/repos/yorick2/Magento-2-add-products-to-categories-in-admin, please create a GitHub OAuth token to go over the API rate limit
Head to https://github.com/settings/tokens/new?scopes=repo&description=Composer+on+hortibrasbr+2018-03-02+1257
to retrieve a token. It will be stored in "/root/.config/composer/auth.json" for future use by Composer.
```

On Magento 2.2.2 -> Extension Manager:

`Command "show" failed: Failed to clone the git@github.com:yorick2/Magento-2-add-products-to-categories-in-admin.git repository, try running in interactive mode so that you can enter your GitHub credentials [RuntimeException] Failed to execute git clone --mirror 'git@github.com:yorick2/Magento-2-add-products-to-categories-in-admin.git' '/home/admin/public_html/var/composer_home/cache/vcs/git-github.com-yorick2-Magento-2-add-products-to-categories-in-admin.git/' show [--all] [-i|--installed] [-p|--platform] [-a|--available] [-s|--self] [-N|--name-only] [-P|--path] [-t|--tree] [-l|--latest] [-o|--outdated] [-m|--minor-only] [-D|--direct] [--strict] [-f|--format FORMAT] [--] [<package>] [<version>] `

**Comment by yorick2** [comment]
This is to do with the way composer accesses github repositories. The instructions it provides in the are for you to do. 
```
 please create a GitHub OAuth token to go over the API rate limit
Head to https://github.com/settings/tokens/new?scopes=repo&description=Composer+on+hortibrasbr+2018-03-02+1257
to retrieve a token. It will be stored in "/root/.config/composer/auth.json" for future use by Composer.
```
see the comments here for more detail: https://github.com/cachethq/Cachet/issues/1220

If this is an issue you can drop the module in a inside app/code, after removing the package from composer.json. To add the module to this location 
- download the zip copy of the module and unzip it
- rename the folder that is created to AdminProductsToCategory
- go to the app/code folder inside your magento installation 
- create a folder called Paulmillband
- move AdminProductsToCategory into that folder

**Comment by mageuser** [comment]
Im already using it, its a good module, thanks.
