### ISSUE TITLE
Subcategories not listed

### ISSUE THREAD

**Issue by onepack** [yorick2/Magento-2-add-products-to-categories-in-admin#2]
Tried to use it but subcategories seem not to get listed.

**Comment by wjpbill** [comment]
They do get listed but only if they are set to Appear in Menu "Yes"

Anyone got any ideas how to remove this restriction?

**Comment by wjpbill** [comment]
> Tried to use it but subcategories seem not to get listed.

They do get listed but only if they are set to Appear in Menu "Yes"
Anyone got any ideas how to remove this restriction?
