### ISSUE TITLE
Composer install

### ISSUE THREAD

**Issue by killday** [yorick2/Magento-2-add-products-to-categories-in-admin#5]
Hi I really like your extension it save me a lot of time and efforts. Only thing that concern me is that every time I install any other extension using composer first thing I get is:
Reading composer.json of paulmillband/m2-admin-products-to-category (1.0.2)Reading composer.json of paulmillband/m2-admin-products-to-category (1.0.1)
./composer.json has been updated

**Comment by yorick2** [comment]
This is part of how composer works.

Composer manages the modules you have. Composer will look at the compose.json file in the different versions of my module (1.0.1 & 1.0.2) on github and choose the one it needs. Then updates your composer.json file (./composer.json), adding my module to its list. Also it updates composer.lock too, with the version of my module it used.

More detail can be found on the composer website. https://getcomposer.org/
